theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_resizing: true
theme_advanced_resize_horizontal: false
theme_advanced_buttons1:
  - formatselect
  - bold
  - italic
  - underline
  - strikethrough
  - |
  - bullist
  - numlist
  - outdent
  - indent
  - |
  - undo
  - redo
  - |
  - link
  - unlink
  - image
content_css: "/assets/questionnaire.css"